### ISSUE TITLE
Add  rubocop

### ISSUE THREAD

**Issue by XaoGao** [XaoGao/rubywork_ru#1]
At first, we need to add style guide for our project:
1) Add gem to gemfile rubocop in developer group
2) Ruby bundle install in termail
3) Add .rubocop.yml file to main directory
4) In file we need add some settings and rules
```
require:

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Rails/FilePath:
  EnforcedStyle: arguments

Metrics/BlockLength:
  AllowedMethods: ['describe', 'context']
```
